import AppKit

/// NSPasteboard monitor.
/// - Polls changeCount (the only mechanism macOS exposes)
/// - Debounce: collapse many rapid changes into a single tick
final class PasteboardMonitor {

    private let pasteboard = NSPasteboard.general
    private let interval: TimeInterval
    private let debounce: TimeInterval

    /// 6.9 安全:密码管理器(1Password / Bitwarden / Apple Passwords 等)写入
    /// 剪贴板时会同时打这些类型,标记"请不要持久化"。我们在 tick() 头部检测,
    /// 命中就直接跳过——不读 string、不入库、不打 log。
    /// 协议参考:https://nspasteboard.org/
    private static let doNotStoreTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private var lastChangeCount: Int = -1
    private var timer: Timer?
    private var lastEmissionAt: Date = .distantPast

    var onNewItem: ((ClipItemBuilder.Result) -> Void)?

    init(interval: TimeInterval = 0.5, debounce: TimeInterval = 0.15) {
        self.interval = interval
        self.debounce = debounce
    }

    func start() {
        lastChangeCount = pasteboard.changeCount
        schedule()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func schedule() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
        RunLoop.current.add(timer!, forMode: .common)
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // 6.9 安全:尊重密码管理器的"do not store"协议——任一标记命中即跳过整次 tick。
        // 不读 string、不入库、不 log,防止 1Password / Bitwarden / Apple Passwords 等
        // 复制的密码、OTP、seed phrase 进入 Recall 历史。
        let types = pasteboard.types ?? []
        if Self.doNotStoreTypes.contains(where: { types.contains($0) }) {
            AppLog.paste.info("Skipped concealed/transient pasteboard change")
            return
        }

        let now = Date()
        if now.timeIntervalSince(lastEmissionAt) < debounce { return }
        lastEmissionAt = now

        // 6.5 snippet trigger-word detection (isolated on @MainActor)
        let pbString = pasteboard.string(forType: .string)
        if let str = pbString {
            Task { @MainActor in
                if let snippet = SnippetService.matchTrigger(in: str, allItems: SnippetService.allSnippets()) {
                    let trigger = snippet.triggerWord ?? ""
                    AppLog.paste.info("Snippet triggered (trigger len=\(trigger.count, privacy: .public))")
                    SnippetService.recordUsage(snippet)
                    // Real auto-expand: delete the trigger word and write
                    // the snippet at the cursor position
                    PasteService.shared.expandSnippet(
                        triggerLength: trigger.count,
                        snippetText: snippet.textContent ?? ""
                    )
                    return  // snippet path does not write to the database
                }
            }
        }

        guard let result = ClipItemBuilder.build(from: pasteboard) else { return }
        onNewItem?(result)
    }
}
